### PR TITLE
Add HN button

### PR DESCRIPTION
**Pull request by marksteve**

### CODE REVIEW

**Comment by marksteve** [comment]
You can preview it here: http://marksteve.com/flatdoc/

**Comment by rstacruz** [comment]
Nice, thanks for pointing me to hnbutton. :) I think I'd prefer this to be on the left sidebar so it's not as intrusive.

**Comment by marksteve** [comment]
Did that :D Placed it below the star link. Or should it be below the other github links?

**Comment by rstacruz** [comment]
Changed the style a bit to make it fit the GH buttons better. (data-style='twitter')

image

**Comment by marksteve** [comment]
:+1:

**Pull request merged**
