### PR TITLE
Add support for external highlighter

### PR DESCRIPTION
**Pull request by malthe**
An example is included in the code comments for integration with
'highlight.js' (an excellent highlighter):

``` js
Flatdoc.run({
  highlight: function (code, value) {
     return hljs.highlight(lang, code).value;
  },
  ...
 });
```

Note that in addition to this, only the 'generic' highlighter has
been preserved.

The idea being that most people will want to link in 'highlight.js'
because it supports so many more languages.

### CODE REVIEW

**Comment by rstacruz** [comment]
Thanks for this. Actually, I'm totally open to the idea of making highlight.js part of the default flatdoc distribution.

**Comment by rstacruz** [comment]
Thanks for this! I'm gonna release this as 0.8.5 now.

**Comment by rstacruz** [comment]
Ah — hm. looks like it dropped support for js highlighting?

**Comment by rstacruz** [comment]
Added back the default syntax highlighters: c9c9ef6d. This change should still allow you to override your syntax highlighting code, while still retaining the default html/js highlighters.

**Comment by rstacruz** [comment]
Also added some tests for syntax highlighting: 749fa227.

**Comment by malthe** [comment]
I retained only the "generic" highlighter for space reasons, but I guess
that's a separate decision to make.

**Comment by andidev** [comment]
value parameter name should be named lang in configuration example

``` javascript
Flatdoc.run({
  highlight: function (code, lang) {
     return hljs.highlight(lang, code).value;
  },
  ...
 });
```

also it would be nice to have this configuration in the docs. Would also be good to mention that the following imports are needed

``` html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/xcode.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
```

**Pull request merged**
